spring:
  datasource:
    url: 'jdbc:mysql://mysql:3306/hapi_fhir?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true'
    username: root
    password: ${MYSQL_ROOT_PASSWORD:root_dev}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirMySQL8Dialect
      hibernate.format_sql: false
      hibernate.hbm2ddl.auto: update

hapi:
  fhir:
    fhir_version: R4
    allow_multiple_delete: true
    allow_external_references: true
    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'
    cr:
      enabled: true
    cql:
      enabled: true
    mdm:
      enabled: false
    bulk_export_enabled: false
    subscription:
      resthook_enabled: false
      websocket_enabled: false
