spring:
  datasource:
    url: 'jdbc:mysql://document-ai-prod-mysql.cxtyszxlzcsj.us-east-2.rds.amazonaws.com:3306/hapi_fhir?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC'
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirMySQL8Dialect
      hibernate.format_sql: false
      hibernate.search.enabled: false

hapi:
  fhir:
    fhir_version: R4
    allow_multiple_delete: true
    allow_external_references: true
    cors:
      allow_Credentials: true
      allowed_origin:
        - '*'
    cr:
      enabled: true
    cql:
      enabled: true
    mdm:
      enabled: false
    bulk_export_enabled: false
    subscription:
      resthook_enabled: false
      websocket_enabled: false
